### ISSUE TITLE
Can't download alpha builds of Discord

### ISSUE THREAD

**Issue by GrafKiedyOdcinek** [revenge-mod/revenge-manager#9]
It's stuck on Downloading base APK. Can someone tell me how the download process works, so that I can troubleshoot it?

**Comment by PalmDevs** [comment]
Your network is likely blocking the domains the manager is trying to download from.

**Comment by GrafKiedyOdcinek** [comment]
No domains should be blocked, I disabled the custom DNS. It was working recently. Are you able to download the latest alpha builds?

**Comment by oSumAtrIX** [comment]
All builds are provided by the mirrors here: https://github.com/revenge-mod/revenge-manager/blob/097fa954fffd6371170482988a55028e047998e1/app/src/main/java/dev/beefers/vendetta/manager/domain/manager/PreferenceManager.kt#L80-L84

If the download fails, it's probably related to the mirrors. Try accessing the base APK from the mirrors links directly. If it works, reopen this issue.
